kubernetes/babel-downloads.k8s.yaml

This PR increases the size of the babel-downloads PVC as we now require more than 400Gi to complete building the compendia.

Increased babel-downloads size

---

config.json
src/ubergraph.py

Large UberGraph queries continue to time out. This PR adds code to paginate UberGraph queries so that we can retrieve larger result sets.
It also removes EFO from the list of UberGraph ontologies as removed in https://github.com/INCATools/ubergraph/pull/66.

Paginate UberGraph results and remove EFO

---

config.json
src/babel_utils.py
src/createcompendia/taxon.py
src/node.py
src/snakefiles/taxon.snakefile

We identified many UMLS IDs that correspond to taxa but aren't currently imported in https://github.com/TranslatorSRI/NodeNormalization/issues/119#issuecomment-1229860214. This PR updates the taxon compendia to include taxa from UMLS. Since Biolink Model v3.0.2 doesn't include UMLS as an identifier prefix for OrganismTaxon, this PR adds an `extra_prefixes` argument to `write_compendium()` to add `UMLS` to that list, since `UMLS` was added to the Biolink Model OrganismTaxon class (https://github.com/biolink/biolink-model/issues/1084), we don't actually use this functionality here. But I'm leaving it in since we might need it in the future.

Add UMLS IDs to taxon

---

src/datahandlers/drugcentral.py
src/snakefiles/datacollect.snakefile

The CHEBI:CHEBI: bug is caused by DrugCentral adding a `CHEBI:` prefix to its identifier. This PR checks for that prefix and removes it so the rest of our code can work correctly. Since it only works on `CHEBI` entries with the prefix, it should be fairly safe to leave in even if DrugCentral removes the prefix at a later date. Fixes #69.
This also deletes the non-functional `get_drugcentralx` target, which refers to a function that no longer exists in this repository. Closes #77.

Fix CHEBI:CHEBI: bug (#69)

---

src/createcompendia/leftover_umls.py

The previous PR accidentally left out the relation when generating synonyms/umls.txt. This PR restores that.
Fixes #82.

Added relation from UMLS/synonyms into synonyms/umls.txt

---

src/babel_utils.py
src/createcompendia/chemicals.py

This is a quick fix for #83 that splits cliques that contain both a PubChem MolecularMixture and SmallMolecule into two separate cliques, one containing all identifiers that have a type of MolecularMixture, while the other contains all remaining identifiers.
In most cases, only a single PubChem compound is separated, but some cliques have more than one identifiers, such as in the following example:
> WARNING:root:Found a clique that that contains PUBCHEM types ({'biolink:SmallMolecule', 'biolink:MolecularMixture'}). This clique will be split into a biolink:MolecularMixture ({'PUBCHEM.COMPOUND:11149677', 'PUBCHEM.COMPOUND:22836554', 'PUBCHEM.COMPOUND:4066245', 'PUBCHEM.COMPOUND:5373419'}) and a biolink:SmallMolecule ({'CAS:21679-31-2', 'UMLS:C0244965', 'CAS:17272-66-1', 'MESH:C049529', …

Split cliques that contain both MolecularMixtures and SmallMolecules

---

src/createcompendia/gene.py
src/createcompendia/protein.py
src/datahandlers/ensembl.py
src/node.py

This PR modifies the ENSEMBL identifiers we get from BioMart so that versioned identifiers (e.g. `ENSEMBL:ENSP00000263368.3`) are treated as identical to the non-versioned identifier (in this case, `ENSEMBL:ENSP00000263368`). Note that this will not apply to ENSEMBL identifiers we get from any other source, but I think most of our ENSEMBL identifiers are from BioMart.
Relates to #72.

Treat ENSEMBL versioned identifier as identical to their non-versioned representation

---

src/datahandlers/hmdb.py

When an HMDB metabolite has a single synonym, a bug in the code caused each character from that synonym to be treated as a separate synonym (see #103). This PR fixes that by checking for that case and changing a single synonym into a one-element list.

Fix bug in HMDB metabolites with a single synonym

---

kubernetes/babel-outputs.k8s.yaml
src/babel_utils.py
src/createcompendia/leftover_umls.py
src/datahandlers/ncbigene.py
src/snakefiles/leftover_umls.snakefile

Changes the structure of the synonyms files to 
1. Be in jsonl format 
2. include a preferred_name label
3. include biolink types
This new style can be loaded into the prototype name resolver.
While working on this PR, we also fixed a bug in NCBIGene synonym generation.

change syn file format

---

src/node.py

SynonymFactory uses `Text.get_curie()` to retrieve the uppercased version of the prefix, which can cause a problem when attempting to access a folder for a prefix that isn't uppercased (such as `NCBIGene`, which the current code incorrectly looks up at `babel_downloads/NCBIGENE/synonyms`). This PR replaces that with a call to `Text.get_prefix()`, which does not uppercase the prefix, and so retrieves the synonyms correctly.
There is one outstanding question, which we can fix in this PR or file as a separate issue:
Closes #128.

Fix capitalization bug in SynonymFactory

---

src/snakefiles/anatomy.snakefile
src/snakefiles/chemical.snakefile
src/snakefiles/diseasephenotype.snakefile
src/snakefiles/gene.snakefile
src/snakefiles/genefamily.snakefile
src/snakefiles/macromolecular_complex.snakefile
src/snakefiles/process.snakefile
src/snakefiles/protein.snakefile
src/snakefiles/taxon.snakefile

This PR adds the synonym files as inputs to the final completion task. This allows them to be regenerated simply by deleting them and re-running snakemake.
Should be merged after PR #130.

Make synonym outputs explicit inputs to other rules in Snakemake

---

src/babel_utils.py
src/datahandlers/obo.py
src/node.py
src/snakefiles/datacollect.snakefile
src/ubergraph.py

This PR adds code to retrieve descriptions from UberGraph and incorporate them into the compendia being generated.
It generates descriptions in the format:
```json
{
"type": "biolink:Disease",
"ic": "100",
"identifiers": [{"i": "UMLS:C5235953", "l": "Locally Advanced Ewing Sarcoma"}, {"i": "NCIT:C164080", "l": "Locally Advanced Ewing Sarcoma"}],
"descriptions": ["Ewing sarcoma that has spread from its original site of growth to nearby tissues or lymph nodes."]
}
{
"type": "biolink:Disease",
"ic": "100",
"identifiers": [{"i": "MONDO:0011613", "l": "autosomal recessive early-onset Parkinson disease 6"}, {"i": "DOID:0060369", "l": "Parkinson's disease 6"}, {"i": "OMIM:605909"}, {"i": "UMLS:C1853833", "l": "Parkinson Disease 6, Autosomal Recessive Early-Onset"}, {"i": "UMLS:C1970035", "l": …
```

Generate descriptions for all identifiers from UberGraph

---

src/babel_utils.py
src/createcompendia/anatomy.py
src/createcompendia/chemicals.py
src/createcompendia/diseasephenotype.py
src/createcompendia/gene.py
src/createcompendia/genefamily.py
src/createcompendia/macromolecular_complex.py
src/createcompendia/processactivitypathway.py
src/createcompendia/protein.py
src/createcompendia/taxon.py
src/datahandlers/obo.py
src/node.py
src/snakefiles/anatomy.snakefile
src/snakefiles/chemical.snakefile
src/snakefiles/datacollect.snakefile
src/snakefiles/diseasephenotype.snakefile
src/snakefiles/gene.snakefile
src/snakefiles/genefamily.snakefile
src/snakefiles/macromolecular_complex.snakefile
src/snakefiles/process.snakefile
src/snakefiles/protein.snakefile
src/snakefiles/taxon.snakefile
src/ubergraph.py

We previously had a local copy of this download -- the `input_data/icRDF.tsv` file -- which had to be updated manually. This PR generates a new version of this file -- at `babel_downloads/icRDF.tsv` by downloading all the values from Ubergraph and then uses them as needed during compendium writing.
Closes #123.

Download information content values for Ubergraph terms directly from Ubergraph

---

src/babel_utils.py

We sometimes get duplicate synonyms in the output, which I've realized is because `synonym_factory.get_synonyms()` only ensures that `(relation, synonym)` tuples are unique. I've added a `set()` to ensure that the actual synonyms are unique, too. (Split off from PR #165).
Should be merged after PR #166.

Fix synonym uniquification

---

src/babel_utils.py

This PR adds emitting CURIE suffixes in the synonym information for use in NameRes (as used by PR https://github.com/TranslatorSRI/NameResolution/pull/89).

Emit CURIE suffixes in the synonym information

---

config.json

This PR upgrades the Biolink version we use to [Biolink v3.5.4](https://github.com/biolink/biolink-model/releases/tag/v3.5.4) and RxNorm to 08072023.

Upgrade Biolink and RxNorm

---

src/babel_utils.py
src/createcompendia/leftover_umls.py

I'd been previously been keeping identifiers in the synonyms file that have no actual synonyms because I was hoping to implement a feature that would allow people to search by concept identifiers directly in NameRes. But until that functionality exists, we don't need to make the NameRes synonym files larger than they need to be.

Skip writing synonyms that have no valid name

---

Snakefile
config.json
kubernetes/babel-outputs.k8s.yaml
src/exporters/kgx.py
src/snakefiles/datacollect.snakefile
src/snakefiles/exports.snakefile
src/snakefiles/util.py

This PR moves the KGX exporter from NodeNorm (specifically, https://github.com/TranslatorSRI/NodeNormalization/blob/68096b2f16e6c2eedb699178ace71cea98dc794f/node_normalizer/loader.py#L70-L208) into this repo and sets up Snakemake to generate the KGX files with every Babel run.
Closes #61. Closes https://github.com/TranslatorSRI/NodeNormalization/issues/95.

Adds a KGX exporter

---

config.json
requirements.txt
src/babel_utils.py
src/datahandlers/obo.py
src/datahandlers/unii.py
src/node.py
src/snakefiles/datacollect.snakefile

We previously used `Text.obo_to_curie()` to translate the URLs in the information content values we got back from UberGraph into CURIEs. This doesn't work for complex CURIEs such as NCBIGene:4522, which is `https://identifiers.org/ncbigene/4522` (see https://github.com/TranslatorSRI/NodeNormalization/issues/182). This PR provides a warning and an immediate solution, but #226 covers a more long-term tracking option.
This PR uses the [curies](https://github.com/cthoyt/curies) package to translate URLs into CURIEs for us to use. There will still be issues (where Biolink Model and Ubergraph disagree on HTTP vs HTTPS URLs, see https://github.com/biolink/biolink-model/issues/1431), but this should help improve our information content coverage. Since this code needs `get_config()`, which set up …

Fix CURIEs used for information content

---

src/babel_utils.py
src/datahandlers/ncbigene.py
src/node.py
src/snakefiles/datacollect.snakefile

This PR will add taxonomic identifiers to NCBIGene so we can differentiate human and other model organism genes from other cliques.
This PR adds support for extracting NCBI Taxon identifiers from the `NCBIGene/gene_info.gz`, storing it into `NCBIGene/taxa` in a simple tab-delimited format (`CURIE for NCBIGene\tCURIE for NCBITaxon`), adds a TaxonFactory for reading `taxa` files, and adds instructions for writing taxon information into compendium and synonym files.
Should help with TranslatorSRI/NameResolution#92.
In the current Babel run, we don't appear to have any genes with multiple taxa. We have 3,434,997 genes without any taxon information and 49,002,680 genes with one taxon. In compendia files, taxon information is stored per-identifier and per-clique. For example:
```json
{
"type": …
```

Add taxa to NCBIGene

---

Snakefile
src/babel_utils.py
src/exporters/sapbert.py
src/snakefiles/exports.snakefile
src/snakefiles/reports.snakefile
src/snakefiles/util.py

This PR moves the SAPBERT training data exporter into Babel from [Babel Validation](https://github.com/TranslatorSRI/babel-validation/blob/f21b1b308e54ec0af616f2c24f7e2738ac4c261c/src/main/scala/org/renci/babel/utils/converter/Converter.scala#L107-L207). This has been added as a new `exporter` and, as with the KGX file, generates SAPBERT training data that is already gzipped to save space on the Babel instance.
It also includes some minor changes to the babel_utils.py and moved the lists of all Snakemake synonym files into snakesfiles/util.py.

Move SAPBERT training data exporter into Babel

---

.github/workflows/release.yaml
Dockerfile
config.json

Babel used to use renciorg/renci-python-image:latest, but this is still on Python 3.9, which is causing issues with one of our dependencies. This PR upgrades that to [python:latest](https://hub.docker.com/_/python), which should give up Python 3.12+.
This PR also updates Biolink Model to 4.1.6 and RxNorm to 03042024.

Switched Dockerfile to Python 3.12

---

src/datahandlers/ncbigene.py
src/datahandlers/ncbitaxon.py

ncbi.nih.gov has changed to ncbi.nlm.nih.gov. This PR updates URLs in Babel.

Rename ncbi.nih.gov is now ncbi.nlm.nih.gov

---

src/babel_utils.py
src/synonyms/synonymconflation.py

We discussed that we might be able to improve how we use UMLS by incorporating the clique count into the search, i.e. if multiple synonyms have the same score, the one with the higher clique count should be sorted higher up. This PR modifies Babel to include the clique identifier count (as `clique_identifier_count`) in synonym files. It also fixes a minor bug in which conflated synonym files did not get the correct taxon information set on them.

Add clique identifier count to synonyms

---

scripts/babel-build.sh
src/snakefiles/reports.snakefile
src/snakefiles/util.py

This PR includes two minor fixes to Babel:
- We turn off verbose mode -- this didn't previously work, but now it does, and boy is it verbose.
- My plan to move drug-conflated synonyms into an alternate directory has failed (https://github.com/TranslatorSRI/Babel/pull/248), so this PR reverts the appropriate report and checks whether the duplicated synonym files are in the `synonyms/` directory.

Minor fixes

---

src/datahandlers/ec.py
src/datahandlers/efo.py
src/datahandlers/kegg.py

For EFO with language codes, edit them out of the labels. We currently ignore language codes, although in the future we might want to filter to English labels. Closes #271.
This PR also:
- replaces nihilism.com with example.org to make it clearer that it is intended as a stand-in.
- fixes an unrelated regex in KEGG that I noticed because of a warning.

Fix EFO labels and misc fixes

---

config.json
input_data/manual_concords/disease.txt
src/createcompendia/diseasephenotype.py
src/snakefiles/diseasephenotype.snakefile

Searching for both "opioid use disorder" and "alcohol use disorder" would result in a long list of UMLS identifiers for many fine gradations of these concepts. This PR adds some manually-written concords for Disease and PhenotypicFeature to collect some of these identifiers into larger cliques. With these changes, "opioid use disorder" returns [MONDO:0005530 "opiate dependence"](http://purl.obolibrary.org/obo/MONDO_0005530) and "alcohol use disorder" returns [MONDO:0007079 "alcohol dependence"](http://purl.obolibrary.org/obo/MONDO_0007079).
The manual concords are written in a file that is similar to the other concords files, but with support for treating lines starting with `[any whitespace]*#` as comments. I'm not going to put much thought into this at the moment but if we need to do a …

Add manual concords for Disease to improve Opioid and Alcohol Use Disorder

---

src/node.py

Also, a missing prefix now raises an exception.
Closes #263.

Removed special-cased Biolink prefixes

---

input_data/manual_concords/drugchemical.tsv
kubernetes/babel-outputs.k8s.yaml
src/createcompendia/drugchemical.py
src/exporters/duckdb_exporters.py
src/snakefiles/drugchemical.snakefile

This PR adds a manual concord for DrugChemicalConflation, which is incorporated into the process by which DrugChemicalConflation is generated. I've added some examples, including the multiple insulins we've been asked to combine into a single clique.
Should be merged after PR #290.

Add a manual concord for DrugChemicalConflation

---

src/createcompendia/protein.py
src/snakefiles/protein.snakefile

This PR adds taxon information to proteins by extracting UniProtKB to NCBITaxon mappings from the UniProtKB mapping file. The TaxonFactory should automatically include taxon information in the Protein cliques.

Add taxon information to proteins

---

config.json
src/datahandlers/ncbigene.py
src/exporters/sapbert.py

The Translator Hammerhead release of Babel. In addition to other PRs, we only make three minor changes:
- Upgraded RxNorm to 09032024.
- Changed NCBIGene download from FTP to HTTP.
- Increased DRUG_CHEMICAL_SMALLER_MAX_LABEL_LENGTH (introduced in #330) from 30 to 40.

Babel 1.8 (Translator Hammerhead)

---

src/createcompendia/anatomy.py

This PR fixes an edge case that showed up in the latest Babel run: sometimes the prefix is not found in types at all.

Try to fix an issue in anatomy

---

Snakefile
src/exporters/duckdb_exporters.py
src/snakefiles/duckdb.snakefile

This PR adds a prefix report that should be more useful in comparing one Babel run with another.
The output this produced for Babel 1.9 (#365) is: 
[prefix_report-dev-2025jan23.json](https://github.com/user-attachments/files/18515797/prefix_report-dev-2025jan23.json) and [prefix_report.txt](https://github.com/user-attachments/files/18515813/prefix_report.txt) (actually a TSV file).
Closes #359.

Check duplicate prefixes

---

config.json
src/datahandlers/uniprotkb.py
src/snakefiles/datacollect.snakefile

This PR incorporates the UMLS_UniProtKB mappings from https://github.com/cbizon/UMLS_UniProtKB into the gene and protein concords so they can be incorporated into Babel. We only use UMLS/NCBIGene and UMLS/UniProtKB mappings -- we do NOT currently include NCBIGene/UniProtKB mappings for use in the GeneProtein conflation, because we get those from UniProtKB and should include these mappings anyway.
Note also that we could expect the number of duplicate IDs to go _up_ if we are ingesting some of these UMLS identifiers in the chemical build as well.
WIP: needs to be tested.

Incorporate UMLS_UniProtKB mappings

---

src/exporters/sapbert.py

We don't actually need DrugChemicalSmaller.txt.gz to train SAPBERT, so I'm going to add a flag to turn off generating this file (I'll leave the code around so we can turn it back on if we ever need it again).
Closes #412.

Added an in-file config for DrugChemicalSmaller.txt.gz

---

src/snakefiles/anatomy.snakefile
src/snakefiles/chemical.snakefile
src/snakefiles/diseasephenotype.snakefile
src/snakefiles/drugchemical.snakefile
src/snakefiles/gene.snakefile
src/snakefiles/genefamily.snakefile
src/snakefiles/leftover_umls.snakefile
src/snakefiles/macromolecular_complex.snakefile
src/snakefiles/process.snakefile
src/snakefiles/protein.snakefile
src/snakefiles/taxon.snakefile
src/snakefiles/util.py

We can compress all the synonym files, which will save us some disk space.
Ideally, we'd also compress the compendia files, but we need to split those for loading. So maybe it would make sense to split those here?
Partially solves #125.

Gzip synonyms files

---

src/createcompendia/publications.py
src/snakefiles/publications.snakefile

We have been seeing increasing numbers of errors in our PubMed downloads. Since those downloads include MD5 files, we can verify whether we have the correct files and redownload any that are incorrect (via HTTP this time) without too much difficulty. Closes https://github.com/TranslatorSRI/Babel/issues/352.

Add PubMed Verifier

---

src/createcompendia/publications.py

We should delete the files before redownloading them, but if we did that and the download failed, we would not retry the download again. So instead, we truncate both files -- this should cause MD5 verification to fail until they are in sync again.

Replace file deletion with file truncation

---

Snakefile
src/createcompendia/leftover_umls.py
src/exporters/duckdb_exporters.py
src/exporters/sapbert.py
src/snakefiles/cell_line.snakefile
src/snakefiles/drugchemical.snakefile
src/snakefiles/duckdb.snakefile
src/snakefiles/exports.snakefile
src/snakefiles/leftover_umls.snakefile
src/snakefiles/publications.snakefile
src/snakefiles/reports.snakefile
src/snakefiles/util.py
src/synonyms/synonymconflation.py

Actually running the synonym compression code in Babel v1.10.0 (https://github.com/TranslatorSRI/Babel/pull/424) revealed that it wasn't working properly. This PR should fix that.

Fix synonyms compression

---

releases/2025jan23.md
releases/2025mar31.md

This PR adds the database sizes for Babel 2025jan23 and 2025mar31 for both NodeNorm and NameRes.

Added database sizes for Babel 2025jan23 and 2025mar31, including NameRes Solr

---

src/createcompendia/chemicals.py
src/createcompendia/diseasephenotype.py
src/createcompendia/processactivitypathway.py
src/datahandlers/umls.py

This PR adds a `blocklist_umls_semantic_type_tree` parameter to `write_umls_ids()`, in addition to the existing `blocklist_umls_ids` parameter. The former is a list of UMLS semantic type trees (e.g. `A1.4.1.2.1.7: Amino Acid, Peptide, or Protein`), while the latter is a list of individual UMLS IDs that should be skipped. Because each UMLS ID can have multiple semantic types, we need to load all the potential UMLS IDs into memory along with all its semantic types, so we can determine whether or not we need to block it.

Add a semantic type blocklist to write_umls_ids()

---

src/babel_utils.py
src/createcompendia/drugchemical.py
src/createcompendia/leftover_umls.py
src/datahandlers/drugbank.py
src/datahandlers/ensembl.py
src/datahandlers/obo.py
src/datahandlers/unii.py
src/exporters/duckdb_exporters.py
src/exporters/sapbert.py
src/node.py
src/util.py

This is to ensure that we always load the configured version. I also moved some utility functions into `utils.py`.
Closes #447.

Create get_biolink_model_toolkit() utility function

---

src/node.py

It turns out that we were doing string comparisons on information content values instead of float comparisons. This PR fixes that.

Fix information content comparisons (float instead of string)

---

src/createcompendia/leftover_umls.py
src/datahandlers/umls.py

This PR fixes several UMLS bugs:
- Accidentally imported snakemake.logging.Logger instead if our Babel Logger. Replaced with simple logging itself, since I'll do that as the standard thing.
- No longer load semantic types and semantic type trees for CURIEs that are blocked by `blocklist_umls_ids`.
- Instead of writing out every Biolink type for a CURIE, we only write out the one mapped from the first UMLS type to appear in the file.

Fix some UMLS bugs

---

config.yaml
src/datahandlers/obo.py
src/snakefiles/datacollect.snakefile
src/ubergraph.py

We now store all UberGraph labels and synonyms in a single location (`${babel_downloads}/common/ubergraph/(labels|synonyms).jsonl`). However, a bunch of Snakemake steps require the label/synonym files to be generated in the correct places (e.g. `UBERON/labels`, `UBERON/synonyms`) -- AS LONG AS there are no other methods generating these files, it should be safe to do this. This PR adds a configuration option to provide a list of prefixes that we should do this for, and the appropriate code to do this.

Added option to generate prefix labels/synonyms files for some UberGraph prefixes

---

src/createcompendia/chemicals.py

• Modified `combine_unichem` function to only call `remove_overused_xrefs` for specific prefixes
• Now only applies filtering to UNII, KEGG.COMPOUND, and DrugCentral prefixes
• Preserves all cross-references for other prefixes like CHEBI without filtering
We analyzed all the UNICHEM mappings, and the code and results can be found here: https://github.com/cbizon/UniChemCheckup/
Based on this analysis, we determined that overused cross-reference filtering should only be applied to certain prefixes that showed problematic patterns, while maintaining complete mappings for others.

Conditionally apply overused xref filtering in combine_unichem

---

requirements.lock
requirements.txt
src/babel_utils.py
src/createcompendia/protein.py
src/node.py
src/snakefiles/chemical.snakefile
src/util.py

The protein compendia was taking an impossibly long time to run because we've hit our memory limit on Sterling. This PR is intended to help debug that by making two changes:
1. It adds a `get_memory_usage_summary()` function that returns a string summarizing the current memory usage. This isn't perfect -- it returns the node-level memory usage, so the percentage isn't relative to our maximum available memory for our Kubernetes pod. But that still tells us how close we are to running out of memory.
* A bonus goal would be to someday use regexes to find all the memory usage reports throughout the run process so we know how it varies.
2. It adds a bit of code to `write_compendium()` so that it provides clique production rate/time elapsed/remaining time estimated every 1M cliques it produces. …

Debug protein compendium slowdown

---

Snakefile
config.yaml
requirements.txt
src/babel_utils.py
src/createcompendia/protein.py
src/node.py
src/util.py

This PR fixes the slowdown issue by loading config.yaml only once (the first time get_config() is loaded).
It also begins the process of moving away from the overly complicated LoggingUtil.* code and replacing that with `util.get_logger(__name__)`, which just returns a Logger for the current code.
It also improves the output of the `write_compendia()` logging from PR #477, adds a temporary directory under `babel_downloads/`, and fixes some (probably unrelated) bugs in synonym lookups.

Slowdown fix and improved logging

---

src/babel_utils.py
src/createcompendia/chemicals.py
src/metadata/provenance.py
src/properties.py
src/reports/compendia_per_file_reports.py
src/snakefiles/chemical.snakefile
src/snakefiles/drugchemical.snakefile
src/snakefiles/publications.snakefile

The code in PR #473 relies on a Property being hashable (so that it can be added to sets for uniqification), but we currently have a list of sources in there, which can't be easily hashed. This PR turns Property into a frozen dataclass, replaces the single source with a single source as a string, adds some example code for testing, and makes some incidental fixes to the metadata yaml files.
Closes #86. Closes #406. Closes #407.

Fix chemical properties

---

config.yaml
src/snakefiles/geneprotein.snakefile
src/snakefiles/util.py
src/synonyms/synonymconflation.py

This PR adds a new output: `synonyms/GeneProteinConflated.txt`, based on the GeneProtein conflation and the Gene and Protein outputs. It should be pretty similar to the first attempt (PR #185). Also fixes a bug in synonym conflating with taxa that we'd never run into because we'd only conflated DrugChemicals before.
Closes https://github.com/TranslatorSRI/NameResolution/issues/191.

Add GeneProtein conflated synonyms

---

config.yaml
kubernetes/babel.k8s.yaml
scripts/rsync-to-server.sh
src/babel_utils.py
src/createcompendia/chemicals.py
src/exporters/kgx.py
src/node.py
src/properties.py
src/snakefiles/duckdb.snakefile
src/snakefiles/publications.snakefile

Changes in this PR:
* Rewrote part of the HAS_ADDITIONAL_ID logic, so that we add it later in the process so that we can label the additional identifiers without them getting re-sorted by `node_factory.create_node()`.
* Modified the description factory so that it processes lists of identifiers instead of a node.
* Increased ephemeral storage for the Babel pod to 1G so we have a bit more spare capacity before we run out of ephemeral space.
* Made DuckDB files non-temporary (so we don't have to regenerate them if we rebuild something), but added an `rsync-to-server.sh` script that excludes the DuckDB files when rsyncing the Babel Outputs to a directory.
* KEGG.COMPOUND cross-references in ChEBI are now a list instead of a single ID, which need to be handled separately. Closes #493 …

Babel v1.12.0
